name: ðŸ› ï¸ Build image 
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        versions: ["23.5", "23.6"]
        flavors: ["f", "r", "s"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Download install file
        run: |
          echo "${{ secrets.FILE_USER_AUTH }}" > k
          chmod go-r k
          sftp -i k ${{ secrets.FILE_USER }}@${{ secrets.FILE_SERVER }} <<< "get oracle-database-free-23ai-${{ matrix.versions }}-1.0-1.el8.$(uname -m).rpm"
          rm k

      - name: ðŸ› ï¸ Build container image for ${{ matrix.versions }}, flavor "${{ matrix.flavors }}"
        run: ./buildContainerImage.sh -v "${{ matrix.versions }}" -"${{ matrix.flavors }}

      - name: ðŸ› ï¸ Build faststartcontainer image for ${{ matrix.versions }}, flavor "${{ matrix.flavors }}"
        run: ./buildContainerImage.sh -v "${{ matrix.versions }}" -"${{ matrix.flavors }} -x

      - name: ðŸ”¬ Test images
        run: |
          if   [ "${{ matrix.flavors }}" == f]; then image_flavor="-full";
          elif [ "${{ matrix.flavors }}" == f]; then image_flavor="";
          elif [ "${{ matrix.flavors }}" == f]; then image_flavor="-slim";
          else image_flavor="";
          fi;
          if   [ "$(uname -m)" == "aarch64" ]; then image_arch="arm64";
          elif [ "$(uname -m)" == "x86_64" ]; then image_arch="amd64";
          else image_arch="";
          fi;
          ./test-container.sh "gvenzl/oracle-free:${{ matrix.versions }}image_flavor-$image_arch"
          ./test-container.sh "gvenzl/oracle-free:${{ matrix.versions }}image_flavor-faststart-$image_arch"

