name: ðŸ› ï¸ Build and release all images
on:
  push:
    paths:
      - '.github/**'
    branches-ignore:
      - main
jobs:

  set-constants:
    name: ðŸ”  Setting workflow constants
    runs-on: ubuntu-24.04
    outputs:
      FLAVORS: '[ "f", "r", "s" ]'
      # Make sure that the latest version stays on the right so that it is built last
      # This will ensure that the latest versions appear on top in GitHub and DockerHub.
      VERSIONS: '[ "23.9", "23.26.0" ]'
      LATEST_VERSION: "23.26.0"
      RPM_ARCH: '[ "aarch64", "x86_64" ]'
      IMAGE_ARCH: '[ "amd64", "arm64" ]'
    steps:
      - run: echo "setting constants"

  download-install-files:
    name: â¬‡ï¸ Download install binaries
    environment: build
    runs-on: ubuntu-24.04
    needs: set-constants
    strategy:
      matrix:
        versions: ${{ fromJSON(needs.set-constants.outputs.VERSIONS) }}
        arch: ${{ fromJSON(needs.set-constants.outputs.RPM_ARCH) }}
    steps:
      - name: ðŸ” Determine RPM file name
        run: |
          # Retrieve the version being built
          VERSION="${{ matrix.versions }}"
          if [ "${#VERSION}" == 4 ]; then
            DATABASE_NAME="oracle-database-free-23ai"
          else
            DATABASE_NAME="oracle-ai-database-free-26ai"
          fi;
          echo "DATABASE_NAME=${DATABASE_NAME}" >> "$GITHUB_ENV"

      - name: â¬‡ï¸ Download install file from web
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.FILE_SERVER }} >> ~/.ssh/known_hosts 2>/dev/null
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.FILE_USER_AUTH }}"
          scp ${{ secrets.FILE_USER }}@${{ secrets.FILE_SERVER }}:"${{ env.DATABASE_NAME }}-${{ matrix.versions }}-1.el8.${{ matrix.arch }}.rpm" .

      - name: ðŸ’¾ Store install file
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: ${{ env.DATABASE_NAME }}-${{ matrix.versions }}-1.el8.${{ matrix.arch }}.rpm
          path: ${{ env.DATABASE_NAME }}-${{ matrix.versions }}-1.el8.${{ matrix.arch }}.rpm

  build-and-test-images:
    # Faststart images are built from the same image layers as non-faststart so that layers can be shared
    # Steps:
    # 1)  Download RPM file
    # 2)  Build regular image
    # 3)  Delete RPM file to save space
    # 4)  Test regular image
    # 5)  Export regular image
    # 6)  Upload regular image
    # 7)  Delete regular image export to save space
    # 8)  Build faststart image (regular image could be deleted to save space, already uploaded)
    # 9)  Test faststart image
    # 10) Export faststart image
    # 11) Upload faststart image
    
    name: ðŸ› ï¸ ðŸ”¬ Build and test images
    runs-on: ${{ matrix.os }}
    environment: build
    needs: [ set-constants, download-install-files ]
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        versions: ${{ fromJSON(needs.set-constants.outputs.VERSIONS) }}
        flavors: ${{ fromJSON(needs.set-constants.outputs.FLAVORS) }}
    steps:
      - name: ðŸ“‚ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ”„ Generate environment variables
        id: env_vars
        run: |
          if     [ "${{ matrix.flavors }}" == "f" ]; then image_flavor="-full";
            elif [ "${{ matrix.flavors }}" == "r" ]; then image_flavor="";
            elif [ "${{ matrix.flavors }}" == "s" ]; then image_flavor="-slim";
            else image_flavor="";
          fi;
          echo "IMAGE_FLAVOR=$image_flavor" >> "$GITHUB_OUTPUT"
          os_arch=$(uname -m)
          if     [ "${os_arch}" == "aarch64" ]; then image_arch="arm64";
            elif [ "${os_arch}" == "x86_64" ];  then image_arch="amd64";
            else image_arch="";
          fi;
          echo "IMAGE_ARCH=$image_arch" >> "$GITHUB_OUTPUT"
          echo "OS_ARCH=$os_arch" >> "$GITHUB_OUTPUT"

          # Retrieve the version being built
          VERSION="${{ matrix.versions }}"
          if [ "${#VERSION}" == 4 ]; then
            DATABASE_NAME="oracle-database-free-23ai"
          else
            DATABASE_NAME="oracle-ai-database-free-26ai"
          fi;
          echo "DATABASE_NAME=${DATABASE_NAME}" >> "$GITHUB_ENV"

      - name: â¬‡ï¸ Download stored install file
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DATABASE_NAME }}-${{ matrix.versions }}-1.el8.${{ steps.env_vars.outputs.OS_ARCH }}.rpm

      - name: ðŸ› ï¸ Build container image for ${{ matrix.versions }}, flavor "${{ matrix.flavors }}"
        run: ./buildContainerImage.sh -v "${{ matrix.versions }}" -${{ matrix.flavors }}

      - name: ðŸ§¹ Cleanup build rpm
        # RPM file is no longer needed, save some space
        run: rm ${{ env.DATABASE_NAME }}-${{ matrix.versions }}-1.el8.${{ steps.env_vars.outputs.OS_ARCH }}.rpm

      - name: ðŸ”¬ Test non-faststart image
        env:
          IMAGE_FLAVOR: ${{ steps.env_vars.outputs.IMAGE_FLAVOR }}
          IMAGE_ARCH: ${{ steps.env_vars.outputs.IMAGE_ARCH }}
        run: |
          cd tests
          ./test-container.sh "gvenzl/oracle-free:${{ matrix.versions }}${IMAGE_FLAVOR}-${IMAGE_ARCH}"
          cd ..

      - name: ðŸ“¤ Export regular image to local file system
        env:
          IMAGE_FLAVOR: ${{ steps.env_vars.outputs.IMAGE_FLAVOR }}
          IMAGE_ARCH: ${{ steps.env_vars.outputs.IMAGE_ARCH }}
        run: podman save -o "oracle-free-${{ matrix.versions }}${IMAGE_FLAVOR}-${IMAGE_ARCH}.tar" "localhost/gvenzl/oracle-free:${{ matrix.versions }}${IMAGE_FLAVOR}-${IMAGE_ARCH}"

      - name: â¬†ï¸ Upload image non-faststart image for deploy job
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: oracle-free-${{ matrix.versions }}${{ steps.env_vars.outputs.IMAGE_FLAVOR }}-${{ steps.env_vars.outputs.IMAGE_ARCH }}
          path: oracle-free-${{ matrix.versions }}${{ steps.env_vars.outputs.IMAGE_FLAVOR }}-${{ steps.env_vars.outputs.IMAGE_ARCH }}.tar

      - name: ðŸ§¹ Cleanup non-faststart image export
        # Non-faststart image is no longer needed, save some space
        run: rm oracle-free-${{ matrix.versions }}${{ steps.env_vars.outputs.IMAGE_FLAVOR }}-${{ steps.env_vars.outputs.IMAGE_ARCH }}.tar

      - name: ðŸ› ï¸ Build faststart container image for ${{ matrix.versions }}, flavor "${{ matrix.flavors }}"
        run: ./buildContainerImage.sh -i -v "${{ matrix.versions }}" -${{ matrix.flavors }} -x

      - name: ðŸ”¬ Test faststart image
        env:
          IMAGE_FLAVOR: ${{ steps.env_vars.outputs.IMAGE_FLAVOR }}
          IMAGE_ARCH: ${{ steps.env_vars.outputs.IMAGE_ARCH }}
        run: |
          cd tests
          ./test-container.sh "gvenzl/oracle-free:${{ matrix.versions }}${IMAGE_FLAVOR}-faststart-${IMAGE_ARCH}"
          cd ..

      - name: ðŸ“¤ Export faststart image to local file system
        env:
          IMAGE_FLAVOR: ${{ steps.env_vars.outputs.IMAGE_FLAVOR }}
          IMAGE_ARCH: ${{ steps.env_vars.outputs.IMAGE_ARCH }}
        run: podman save -o "oracle-free-${{ matrix.versions }}${IMAGE_FLAVOR}-faststart-${IMAGE_ARCH}.tar" "localhost/gvenzl/oracle-free:${{ matrix.versions }}${IMAGE_FLAVOR}-faststart-${IMAGE_ARCH}"

      - name: â¬†ï¸ Upload image faststart image for deploy job
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: oracle-free-${{ matrix.versions }}${{ steps.env_vars.outputs.IMAGE_FLAVOR }}-faststart-${{ steps.env_vars.outputs.IMAGE_ARCH }}
          path: oracle-free-${{ matrix.versions }}${{ steps.env_vars.outputs.IMAGE_FLAVOR }}-faststart-${{ steps.env_vars.outputs.IMAGE_ARCH }}.tar

  upload-platform-images:
    name: â¬†ï¸ ðŸ“‹ Upload platform images to registries
    environment: upload
    runs-on: ubuntu-24.04
    needs: [ set-constants, build-and-test-images ]

    permissions:
      packages: write

    strategy:
      matrix:
        repository: [ "ghcr.io/${{ github.repository_owner }}/test", "ghcr.io/${{ github.repository_owner }}/test2" ]
        versions: ${{ fromJSON(needs.set-constants.outputs.VERSIONS) }}
        arch: ${{ fromJSON(needs.set-constants.outputs.IMAGE_ARCH) }}
        flavor: [ "-full", "", "-slim" ] # "" is the "regular" image
        type: [ "", "-faststart" ] # "" is the non-faststart image

    steps:
      - name: â¬‡ï¸ Download image image
        uses: actions/download-artifact@v4
        with:
          name: oracle-free-${{ matrix.versions }}${{ matrix.flavor }}${{ matrix.type }}-${{ matrix.arch }}

      - name: ðŸ“¥ Import image
        run: podman load -i oracle-free-${{ matrix.versions }}${{ matrix.flavor }}${{ matrix.type }}-${{ matrix.arch }}.tar

      - name: ðŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ðŸ”“ Login to Docker.io registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PWD }}
          registry: docker.io

      - name: ðŸ«¸ Push image to  Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ matrix.repository }}
          image: oracle-free
          tags: ${{ matrix.versions }}${{ matrix.flavor }}${{ matrix.type }}-${{ matrix.arch }}

  create-latest-version-tags:
    name: â¬†ï¸ ðŸ“‹ Upload latest images to registries
    environment: tag
    runs-on: ubuntu-24.04
    needs: [ set-constants, upload-platform-images ]

    permissions:
      packages: write

    strategy:
      matrix:
        repository: [ "ghcr.io/${{ github.repository_owner }}/test", "ghcr.io/${{ github.repository_owner }}/test2" ]
        arch: ${{ fromJSON(needs.set-constants.outputs.IMAGE_ARCH) }}
        flavor: [ "-full", "", "-slim" ] # "" is the "regular" image
        type: [ "", "-faststart" ] # "" is the non-faststart image

    steps:
      - name: â¬‡ï¸ Download image
        uses: actions/download-artifact@v4
        with:
          name: oracle-free-${{ fromJSON(needs.set-constants.outputs.LATEST_VERSION) }}${{ matrix.flavor }}${{ matrix.type }}-${{ matrix.arch }}

      - name: ðŸ“¥ Import image
        run: podman load -i oracle-free-${{ fromJSON(needs.set-constants.outputs.LATEST_VERSION) }}${{ matrix.flavor }}${{ matrix.type }}-${{ matrix.arch }}.tar

      - name: ðŸ·ï¸ Tag images
        id: tag-images
        env:
          LATEST_VERSION: ${{ fromJSON(needs.set-constants.outputs.LATEST_VERSION) }}
          FLAVOR: ${{ matrix.flavor }}
          ARCH: ${{ matrix.arch }}
          TYPE: ${{ matrix.type }}
        run: |
          # Tag 23[-full | -slim][-faststart]
          podman tag gvenzl/oracle-free:${LATEST_VERSION}${FLAVOR}-faststart-${ARCH} oracle-free:23${FLAVOR}${TYPE}-${ARCH}

          # Tag [-latest] or [-slim | -full]
          if [[ "${FLAVOR}" == "" ]]; then # regular image
            FLAVOR_NO_DASH="latest"
            podman tag gvenzl/oracle-free:${LATEST_VERSION}-faststart-${ARCH} oracle-free:${FLAVOR_NO_DASH}${TYPE}-${ARCH}
          else
            FLAVOR_NO_DASH=${FLAVOR:1}
            podman tag gvenzl/oracle-free:${LATEST_VERSION}${FLAVOR}-faststart-${ARCH} oracle-free:${FLAVOR_NO_DASH}${TYPE}-${ARCH}
          fi;
          # Store value for push
          echo "FLAVOR_NO_DASH=${FLAVOR_NO_DASH}" >> $GITHUB_OUTPUT

      - name: ðŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ðŸ”“ Login to Docker.io registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PWD }}
          registry: docker.io

      - name: ðŸ«¸ Push 23 image to Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ matrix.repository }}
          image: oracle-free
          tags: 23${{ matrix.flavor }}${{ matrix.type }}-${{ matrix.arch }}

      - name: ðŸ«¸ Push versionless faststart image to GitHub Container Registry
        id: push-versionless-faststart-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ matrix.repository }}
          image: oracle-free
          tags: ${{ steps.tag-images.outputs.FLAVOR_NO_DASH }}${{ matrix.type }}-${{ matrix.arch }}

  create-versioned-manifests-tags:
    name: ðŸ“‹ Create versioned manifests to registries
    environment: tag
    runs-on: ubuntu-24.04
    needs: [ set-constants, create-latest-version-tags ]
    strategy:
      matrix:
        repository: [ "ghcr.io/${{ github.repository_owner }}/test", "ghcr.io/${{ github.repository_owner }}/test2" ]
        version: ${{ fromJSON(needs.set-constants.outputs.VERSIONS) }}
        image_flavor: [ "-full", "", "-slim" ]
        image_faststart: [ "-faststart", "" ]

    permissions:
      packages: write

    steps:

      - name: ðŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ðŸ”“ Login to Docker.io registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PWD }}
          registry: docker.io

      - name: ðŸ«¸ Push multi-arch manifest
        run: |
          podman manifest create ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }}
          podman manifest add ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }} \
                              ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }}-amd64
          podman manifest add ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }} \
                              ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }}-arm64
          podman push ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }}
          podman manifest rm ${{ matrix.repository }}/oracle-free:${{ matrix.version }}${{ matrix.image_flavor }}${{ matrix.image_faststart }}

  create-23-manifests-tags:
    name: ðŸ“‹ Create 23 manifests to registries
    environment: tag
    runs-on: ubuntu-24.04
    needs: [ set-constants, create-versioned-manifests-tags, create-latest-version-tags ]
    strategy:
      matrix:
        repository: [ "ghcr.io/${{ github.repository_owner }}/test", "ghcr.io/${{ github.repository_owner }}/test2" ]
        image_flavor: [ "-full", "", "-slim" ]
        image_faststart: [ "-faststart", "" ]

    permissions:
      packages: write

    steps:

      - name: ðŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ðŸ”“ Login to Docker.io registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PWD }}
          registry: docker.io

      - name: ðŸ«¸ Push multi-arch manifest
        run: |
          podman manifest create ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }}
          podman manifest add ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }} \
                              ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }}-amd64
          podman manifest add ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }} \
                              ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }}-arm64
          podman push ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }}
          podman manifest rm ${{ matrix.repository }}/oracle-free:23${{ matrix.image_flavor }}${{ matrix.image_faststart }}

  create-latest-manifests-tags:
    name: ðŸ“‹ Create latest manifests to registries
    environment: tag
    runs-on: ubuntu-24.04
    needs: [ set-constants, create-23-manifests-tags, create-versioned-manifests-tags, create-latest-version-tags ]
    strategy:
      matrix:
        repository: [ "ghcr.io/${{ github.repository_owner }}/test", "ghcr.io/${{ github.repository_owner }}/test2" ]
        image_flavor: [ "full", "latest", "slim" ]
        image_faststart: [ "-faststart", "" ]

    permissions:
      packages: write

    steps:

      - name: ðŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ðŸ”“ Login to Docker.io registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PWD }}
          registry: docker.io

      - name: ðŸ«¸ Push multi-arch manifest
        run: |
          podman manifest create ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }}
          podman manifest add ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }} \
                              ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }}-amd64
          podman manifest add ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }} \
                              ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }}-arm64
          podman push ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }}
          podman manifest rm ${{ matrix.repository }}/oracle-free:${{ matrix.image_flavor }}${{ matrix.image_faststart }}

  cleanup:
    name: ðŸ§¹ Cleanup build leftovers
    runs-on: ubuntu-24.04
    needs: [ create-latest-manifests-tags, create-23-manifests-tags, create-versioned-manifests-tags ]
    permissions:
      deployments: write

    steps:
      - name: ðŸ§¹ Cleanup build deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: build
          onlyRemoveDeployments: true

      - name: ðŸ§¹ Cleanup upload deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: upload
          onlyRemoveDeployments: true

      - name: ðŸ§¹ Cleanup tag deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: tag
          onlyRemoveDeployments: true
